### ISSUE TITLE
Issue with 2.0.8 package

### ISSUE THREAD

**Issue by gep13** [dotnetcore-chocolatey/dotnetcore-chocolateypackages#29]
@riezebosch @jberezanski can one of you have a look at this?

https://chocolatey.org/packages/dotnetcore-runtime.install/2.0.8#files

Notice that the data.ps1 file still has a URL link to 2.0.7 download file.

**Comment by gep13** [comment]
As a side note, would it be possible to remove the AU `update.ps1` files from the meta packages that are being pushed?

i.e. here:
https://chocolatey.org/packages/dotnetcore/2.0.8#files
https://chocolatey.org/packages/dotnetcore-runtime/2.0.8

**Comment by riezebosch** [comment]
According to the release . notes that is correct: https://github.com/dotnet/core/blob/master/release-notes/releases.json#L15-L16 😕

**Comment by gep13** [comment]
WAT!

That is in no way confusing!?!?  😢 

So, does that mean that there were no underlying changes in the dotnetcore-runtime, but the overall version number got bumped?

**Comment by riezebosch** [comment]
@gep13  https://github.com/dotnetcore-chocolatey/dotnetcore-chocolateypackages/commit/dce9a6b6521c00d35374d7966b4cd74697a122e1 should fix the issue of Update.ps1 and json files being included in the nupkg's.

**Comment by gep13** [comment]
@riezebosch that is great! Thank you for getting that done! 👍

**Comment by gep13** [comment]
@riezebosch what was the outcome of this?  Has it been fixed?  If so, what was the issue?

**Comment by riezebosch** [comment]
I thought the package is correct because it points to the download location that Microsoft published? As soon as the will publish a new(er) version it will be updated again.

**Comment by gep13** [comment]
@riezebosch okay, so we are saying that there is nothing to do here.  2.0.8 of the outer package, still only install 2.0.7 of the inner one?

**Comment by jberezanski** [comment]
This is a MESS. A ROYAL MESS, even.

From https://github.com/dotnet/core/blob/master/release-notes/releases.json (fragments):

>        "version-runtime": "2.0.8",
>        "version-sdk": "2.1.200",
>        "date": "05/08/18",
>        "dlc-runtime": "https://download.microsoft.com/download/E/F/7/EF7302FE-4F84-4529-9E3A-893450F76501/",
>
>        "runtime-win-x64.exe": "dotnet-runtime-2.0.7-win-x64.exe",
>
>        "hosting-win-x64.exe": "DotNetCore.2.0.8-WindowsHosting.exe",
>
>        "rps-win-x64.exe": "AspNetCore.2.0.8.RuntimePackageStore_x64.exe",

and

>        "version-runtime": "2.0.7",
>        "version-sdk": "2.1.105",
>        "date": "04/17/18",
>        "dlc-runtime": "https://download.microsoft.com/download/A/9/F/A9F8872C-48B2-41DB-8AAD-D5908D988592/",
>
>        "runtime-win-x64.exe": "dotnet-runtime-2.0.7-win-x64.exe",
>
>        "hosting-win-x64.exe": "DotNetCore.2.0.7-WindowsHosting.exe",
>
>        "rps-win-x64.exe": "AspNetCore.2.0.7.RuntimePackageStore_x64.exe",

Notice that the runtime exe file name is the same, but the download url prefix is different.

From https://github.com/dotnet/core/blob/master/release-notes/README.md:

> Latest Updates
> You can download the latest updates for .NET Core.
> .NET Core 2.0.7   <-- this links to https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.200-sdk-download.md

From https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.200-sdk-download.md:

> You can download the Windows Server Hosting installer and run the following command from an Administrator command prompt: DotNetCore.2.0.7-WindowsHosting.exe (Updated to include ASP.NET Core 2.0.8)

and

> If you need to install the Runtime Package Store separately, the following can be used.
AspNetCore.2.0.8.RuntimePackageStore_x64.exe

I've just tried installing https://download.microsoft.com/download/E/F/7/EF7302FE-4F84-4529-9E3A-893450F76501/dotnet-runtime-2.0.7-win-x64.exe and the installed runtime has 2.0.7 all over the place (folder paths, uninstall entries etc.), so it seems to be just a minor, in-place upgrade to 2.0.7 with no effect on version number (Sigh. Thanks, Microsoft.).

So, I believe that the .NET Core 2.0.8 release currently consists of:
- a slightly updated 2.0.7 runtime
- new WindowsHosting and RuntimePackageStore versions 2.0.8
- new SDK version 2.1.200

I think what we should do is:

- [ ] unlist dotnetcore-runtime.* 2.0.8 (because the version number is incorrect - there is no 2.0.8 runtime yet)
- [ ] publish dotnetcore-runtime.* 2.0.7.20180508 (package fix notation) with updated installer link
- [ ] publish dotnetcore-windowshosting 2.0.8.20180508 (package fix notation) with runtime dependency changed to dotnetcore-runtime.install 2.0.7.20180508

This needs to be done manually, because our AU machinery is nowhere near the level of sophistication needed to handle this automatically...

**Comment by jberezanski** [comment]
Okay, a minor correction: the two dotnet-runtime-2.0.7-win-x64.exe files from both urls (from the 2.0.8 and 2.0.7 releases) have the same checksum, so the runtime is not slightly updated - it is, in fact, identical.

Revised TODO list:
- [ ] unlist dotnetcore-runtime.* 2.0.8 (because the version number is incorrect - there is no 2.0.8 runtime yet)
- [ ] publish dotnetcore-windowshosting 2.0.8.20180508 (package fix notation) with runtime dependency changed to dotnetcore-runtime.install 2.0.7

**Comment by jberezanski** [comment]
@riezebosch What do you think? I can do this quickly.

**Comment by gep13** [comment]
@jberezanski I am very much happy to take a back seat on this one, and let you guys decide.  I am nowhere near up to speed on all of this to add anything of relevance.

Thanks you both for looking at this.

**Comment by jberezanski** [comment]
Shoot, I wrote too quickly without checking first: dotnetcore-windowshosting has no dependency on the runtime, so this package does not need fixing. Yay.
Therefore, all that remains to be done is unlisting the 2.0.8 runtime packages. I'll leave 2.0.8 in the streams info files (*.json) in the repo for now, so that the AppVeyor build does not try to do anything unwelcome. I doubt Microsoft will release a 2.0.8 runtime, I believe the next release will be 2.0.9.

**Comment by jberezanski** [comment]
Now chocolatey.org suddenly dislikes me and I am unable to unlist the packages - I got the "Error: Oh no, we broke something!" page after unchecking "List in search results" and clicking "Save" on https://chocolatey.org/packages/dotnetcore/2.0.8/Delete. Now I cannot even view https://chocolatey.org/packages/dotnetcore, because I keep getting "we broke something". Edge and Firefox. 😞 

@gep13 could you please help and try unlisting dotnetcore, dotnetcore-runtime, dotnetcore-runtime.install and dotnetcore-runtime.portable versions 2.0.8?

**Comment by gep13** [comment]
@jberezanski hmm, I am seeing the same issues...

Give me some time and I will see if I can come up with anything...

**Comment by gep13** [comment]
@jberezanski the site is back up and running, and I have unlisted that package version.

**Comment by jberezanski** [comment]
Thanks! I have also successfully unlisted dotnetcore-runtime, dotnetcore-runtime.install and dotnetcore-runtime.portable versions 2.0.8. May I ask what the issue with the site was?

**Comment by gep13** [comment]
@jberezanski from time to time, due to excessive loads on the database, there are issues connecting to the database. we have to run maintenance on the database, to clean things up, in order for it to come back.

**Comment by jberezanski** [comment]
I see, thanks for explaining.
