### ISSUE TITLE
windowshosting packages and ANCM version conflicts

### ISSUE THREAD

**Issue by photoangell** [dotnetcore-chocolatey/dotnetcore-chocolateypackages#61]
I'd love to use chocolately to manage .net and .net core installs on a windows server (running IIS) that I manage, but I'm a bit confused as to what I need to install.

I ended up with some dependency errors around ANCM versions. I had a dig around this issue https://github.com/dotnetcore-chocolatey/dotnetcore-chocolateypackages/issues/45 but am still confused

The server runs a bunch of .net 2.1, 2.2, 3.1 and .net 5.0 web apps through IIS (there may also be console apps in the future running on task scheduler)

What packages do I need to install?
Is it
choco install dotnet-windowshosting
choco install dotnetcore-windowshosting
choco install dotnetcore-2.1-aspnetruntime
choco install dotnetcore-2.2-aspnetruntime

 - or instead of dotnetcore-windowshosting should I install dotnetcore-aspnetruntime?
 - how can I be sure of getting the correct version of aspnetcoremodule with the above options? I think I should need both versions 1 and 2

**Comment by jberezanski** [comment]
I'm glad you were able to figure this out. Yes, this is the correct set of packages.

- for each major.minor .NET version you need to support, you need both the base runtime package and the ASP.NET runtime
  - this will allow you to run console apps as well as ASP.NET apps on the Kestrel server (outside of IIS)
- in order to run ASP.NET apps under IIS: in addition to the above packages, you also need to install the ANCM - this is where things get tricky, because the ANCM is not bound to a specific .NET version (and there are two generations of ANCM, which install independently)
  - for .NET Core 2.1, you need ANCM v1
  - for .NET Core 2.2+, you need ANCM v2

The -windowshosting package is useful only in simple scenarios, really. It does not provide any value on its own, it just causes installation of other packages as dependencies.

**Comment by photoangell** [comment]
Brilliant. Thanks for comfirming my findings. Very reassuring to know I've got the correct set of packages.
